name: UltimateArrow
main: com.nightrosexl.ua.UltimateArrow
version: 0.1
author: L3X-H4x0r
description: The next best minigame!
commands:
  UltimateArrow:
    description: Join a Ultimate Arrow match.
    usage: /ua [join|leave]
    aliases: [ua]